#!/usr/bin/env python3

from __future__ import print_function

import os, time, datetime, re, sys
import itertools
import praw
import saxo

import pprint

def warning(*objs):
    print("WARNING: ", *objs, file=sys.stderr)

subreddit_r = re.compile('[a-zA-Z0-9]+')

def drop_empty(db, tname):
    c = db.connection.cursor()
    urls = c.execute("select url from %s" % tname).fetchone()
    if urls == None:
        c.execute("drop table %s" % tname)
        db.commit()

@saxo.command()
def r(arg):
    if not arg:
        return "Fetch links from reddit"
    if not saxo.env("base"):
        return "Sorry, this command requires an IRC instance"
    args = arg.split(' ')
    n = 1
    if len(args) >= 1:
        sname = args[0].lower()
    if len(args) == 2:
        n = int(args[1])
    if n > 8:
        return "Sorry, link count should be less than 9"
    if n < 1:
        return "wat?"
    if not subreddit_r.match(sname):
        return "Sorry, subreddit name must match " + subreddit_r.pattern

    path = os.path.join(saxo.env("base"), "database.sqlite3")
    with saxo.database(path) as db:
        c = db.connection.cursor()
        if not "reddit_stat" in db:
            db['reddit_stat'].create(("name", "text unique"), ("value", str))

        tname = "reddit_%s" % sname
        if not tname in db:
            db[tname].create(('url', 'text unique'), ('req_by', str))

        urls = c.execute("select url from %s where req_by = ''" % tname).fetchmany(n)
        if urls == None or urls == []:
            rtime = c.execute("select value from reddit_stat where name = ?", [tname]).fetchone()
            if rtime != None and rtime[0] == str(datetime.date.today()):
                return "No more %s for today" % sname
            try:
                reddit = praw.Reddit(user_agent='irc_pic_bot')
                s = reddit.get_subreddit(sname).get_hot(limit=32)
                for x in s:
                    if 'imgur.com' in x.url or x.url.endswith(('.jpg', '.jpeg', '.gif', '.png', '.gifv', '.webm')):
                        c.execute("replace into %s values(?, '')" % tname, [x.url])
                db.commit()
            except:
                drop_empty(db, tname)
                return "Something went wrong while fetching urls. Sorry."
            c.execute("replace into reddit_stat values (?, ?)", [tname, str(datetime.date.today())])
            db.commit()
            urls = c.execute("select url from %s where req_by = ''" % tname).fetchmany(n)

        if urls == None or urls == []:
            drop_empty(db, tname)
            return "No more urls. Maybe I can't get any pictures. Maybe you specified bad subreddit. Or maybe reddit is down."

        req_nick = saxo.env("nick").encode('utf-8', 'surrogateescape').decode('utf-8')
        urls = list(itertools.chain(*urls))
        req_nicks = [req_nick] * len(urls)
        vals = list(zip(urls, req_nicks))
        #warning(vals, len(vals))
        c.executemany("replace into %s values (?, ?)" % tname, vals)
        db.commit()

        rurls = ''
        for u in urls:
            if 'imgur.com' in u and u.endswith('.gif'):
                u += 'v'
            rurls += ' ' + u
        return rurls

